modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
#issueTrackerURL=""

[[mods]]
    modId="create_ponder_wonder"
    version="${file.jarVersion}"
    displayName="Create Ponder Wonder"
    #updateJSONURL=""
    authors="Oshgnackgnak, Grimmauld"
    description='''
Exports Create ponders to disk.
'''

[[dependencies.create_ponder_wonder]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_ponder_wonder]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19,)"
    ordering="NONE"
    side="BOTH"